In [2]:
import numpy as np
a=np.array([20,30,40])
b=np.array([50,60,70])
print(a+b)

[ 70  90 110]


In [3]:
l1=[20,30,40]
l2=[50,60,70]
print(l1+l2)

[20, 30, 40, 50, 60, 70]


In [4]:
a=np.array([30,40,50.0])
print(a)

[30. 40. 50.]


In [5]:
a=np.array([[10,20],[30,40]])
print(a)

[[10 20]
 [30 40]]
