In [1]:
import numpy as np
a=np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [38]:
#Slicing in the array

In [3]:
print(a[0:3])

[10 20 30]


In [7]:
b=np.array([[10,20,30],[50,60,70]])
print(b[0,1:3])
print(b[1,1])
print(b[:2,:2])

[20 30]
60
[[10 20]
 [50 60]]


In [46]:
#Functions of array
b=np.array([[10,20,30],[50,60,70]])
print(np.shape(b))
print(np.size(b))
print(np.ndim(b))
print(b.dtype)
print(len(b))
print(b.astype(float))
print(b.dtype)

(2, 3)
6
2
int32
2
[[10. 20. 30.]
 [50. 60. 70.]]
int32


In [47]:
#Mathematical operations
a=np.array([10,20,30])
b=np.array([10])
print(a+b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.sqrt(a))
print(np.exp(a))
print(np.power(a,b))

[20 30 40]
[20 30 40]
[ 0 10 20]
[100 200 300]
[1. 2. 3.]
[3.16227766 4.47213595 5.47722558]
[2.20264658e+04 4.85165195e+08 1.06864746e+13]
[1410065408  797966336  716276736]


In [37]:
#Concatenate
arr1=np.array([[10,20],[40,30]])
arr2=np.array([[1,2],[4,3]])
arr3=(np.concatenate([arr1,arr2],axis = 0))
arr4=(np.concatenate([arr1,arr2],axis = 1))
print(arr3)
print(arr4)

[[10 20]
 [40 30]
 [ 1  2]
 [ 4  3]]
[[10 20  1  2]
 [40 30  4  3]]


In [39]:
print(np.hstack([arr1,arr2]))
print(np.vstack([arr1,arr2]))

[[10 20  1  2]
 [40 30  4  3]]
[[10 20]
 [40 30]
 [ 1  2]
 [ 4  3]]


In [45]:
#Splitting 
a=np.array([10,20,30,40,50,60])
print(np.array_split(a,3))
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.array_split(b,4))
c=(np.array_split(b,3))
print(c[1])

[array([10, 20]), array([30, 40]), array([50, 60])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([], shape=(0, 3), dtype=int32)]
[[4 5 6]]


In [57]:
#Insertionn and deletion
arr=np.array([10,20,30,40])
print(np.append(arr,50))
print(np.insert(arr,2,25))
print(np.delete(arr,3))

[10 20 30 40 50]
[10 20 25 30 40]
[10 20 30]


In [58]:
#in 2D array
arr1=np.array([[1,2],[3,4],[5,6]])
print(np.append(arr1,[7,8]))
print(np.insert(arr1,1,[7,8],axis=0))
print(np.insert(arr1,1,7,axis=1))
print(np.insert(arr1,1,[7,8,9],axis=1))
print(np.delete(arr1,1,axis=0))
print(np.delete(arr1,1,axis=1))

[1 2 3 4 5 6 7 8]
[[1 2]
 [7 8]
 [3 4]
 [5 6]]
[[1 7 2]
 [3 7 4]
 [5 7 6]]
[[1 7 2]
 [3 8 4]
 [5 9 6]]
[[1 2]
 [5 6]]
[[1]
 [3]
 [5]]
