In [5]:
#Sorting
import numpy as np
ar=np.array([5,2,7,6,8,3])
print(np.sort(ar))
arr=np.array([[7,5,8,9],[12,55,98,55]])
print(np.sort(arr))

[2 3 5 6 7 8]
[[ 5  7  8  9]
 [12 55 55 98]]


In [10]:
#Searching
ar=np.array([4,5,6,8,6,1])
x=np.where(ar%2==0)
print(x)
arr=np.array([1,2,3,4,5,6])
y=np.searchsorted(arr,4)
print(y)

(array([0, 2, 3, 4]),)
3


In [13]:
#Filtering
ar=np.array([1,2,3,4,5])
fa=[True,False,False,True,False]
new=ar[fa]
print(new)
fa1=ar%2==0
new1=ar[fa1]
print(new1)

[1 4]
[2 4]


In [19]:
#Aggregating
arr=[1,2,3,4]
print(np.sum(arr))
print(np.size(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

10
4
2.5
4
1
[ 1  3  6 10]
[ 1  2  6 24]


In [23]:
a=[10,20,15,18]
b=[5,4,2,5]
price=np.array([a])
quantity=np.array([b])
print("Price:- ",price,"\n","Quantity:- ",quantity)
print()
c=np.cumprod([price,quantity],axis=0)
print(c)
print("Total :-",c[1].sum())

Price:-  [[10 20 15 18]] 
 Quantity:-  [[5 4 2 5]]

[[[10 20 15 18]]

 [[50 80 30 90]]]
Total :- 250


In [25]:
#Statisttical function
import statistics as stats
a=[10,20,30,40,50,60,70,80,90]
print(np.mean(a))
print(np.median(a))
print(stats.mode(a))
print(np.std(a))
print(np.var(a))

50.0
50.0
10
25.81988897471611
666.6666666666666


In [31]:
#Correlation coefficient (-1 is inverse proportion,1 is for direct proportion and 0 is for no relation )
a=[10,20,15,18]
b=[5,8,6,7]
price=np.array([a])
quantity=np.array([b])
print(np.corrcoef(price,quantity))

[[1.         0.97952609]
 [0.97952609 1.        ]]


In [32]:
a=[10,20,15,18]
b=[10,2,7,4]
price=np.array([a])
quantity=np.array([b])
print(np.corrcoef(price,quantity))

[[ 1.         -0.99084787]
 [-0.99084787  1.        ]]
